repos:
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.50.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs_replace
        args: ['--sort-by-required', '--dest=TERRAFORM.md']
      - id: terraform_validate
      - id: terraform_tflint
      - id: checkov
  - repo: https://github.com/ansible/ansible-lint.git
    rev: v5.1.2
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-merge-conflict
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: trailing-whitespace
